### ISSUE TITLE
[BUG] Inconsistent thickness of overlay

### ISSUE THREAD

**Issue by kotakerdus** [policastro/mondrian#6]
Inconsistent thickness of overlay border, it seems some side thicker some aren't

Also is the value here as in `px`?
```toml
active.thickness = 4
inactive.thickness = 4
```

![Image](https://github.com/user-attachments/assets/a70eba2c-8ecd-4787-af2f-8cb59b484a7d)
